version: '3.7'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rocket-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
    networks:
      - api-rocket-network
    volumes:
      - db:/var/lib/mysql
  
  api-rocket:
    build:
      context: .
    container_name: api-rocket
    ports:
      - 3001:3000
    depends_on: 
      - mysql
    networks:
      - api-rocket-network

networks:
  api-rocket-network:
    # name: api-rocket-network - if network was created outside docker compose (e.g. using docker CLI)
    # external: true - if network was created outside docker compose (e.g. using docker CLI)
    driver: bridge

volumes:
  db: